"""item tracking and units of measurement

Revision ID: 59e8adb20868
Revises: ec6e1728f80d
Created: 2026-09-05 21:30:41.456265
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '59e8adb20868'
down_revision: str | None = 'ec6e1728f80d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_of_measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('name_am', sa.String(length=40), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unit_of_measurements')),
    sa.UniqueConstraint('code', name='unit_code_unique')
    )
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('name_key', sa.String(length=60), nullable=False),
    sa.Column('name_am', sa.String(length=60), nullable=True),
    sa.Column('default_unit_id', sa.Uuid(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['default_unit_id'], ['unit_of_measurements.id'], name=op.f('fk_items_default_unit_id_unit_of_measurements')),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_items_owner_id_owners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    sa.UniqueConstraint('owner_id', 'name_key', name='owner_item_name')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_items_owner_id_is_archived', ['owner_id', 'is_archived'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('quantity_milli', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('unit_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_expenses_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_unit_id'), ['unit_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_expenses_item_id_items'), 'items', ['item_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_expenses_unit_id_unit_of_measurements'), 'unit_of_measurements', ['unit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_expenses_unit_id_unit_of_measurements'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_expenses_item_id_items'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_expenses_unit_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_item_id'))
        batch_op.drop_column('unit_id')
        batch_op.drop_column('quantity_milli')
        batch_op.drop_column('item_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('ix_items_owner_id_is_archived')
        batch_op.drop_index(batch_op.f('ix_items_owner_id'))

    op.drop_table('items')
    op.drop_table('unit_of_measurements')
    # ### end Alembic commands ###
