"""initial schema

Revision ID: ec6e1728f80d
Revises: 
Created: 2026-09-05 00:14:06.424991
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ec6e1728f80d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=False),
    sa.Column('preferred_calendar', sa.String(length=10), nullable=False),
    sa.Column('preferred_language', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_owners'))
    )
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owners_email'), ['email'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('name_key', sa.String(length=60), nullable=False),
    sa.Column('name_am', sa.String(length=60), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_categories_owner_id_owners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('owner_id', 'name_key', name='owner_category_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_categories_owner_id_is_archived', ['owner_id', 'is_archived'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('spent_on', sa.Date(), nullable=False),
    sa.Column('entered_in', sa.String(length=10), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('payment_method', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_expenses_category_id_categories')),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_expenses_owner_id_owners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_expenses_owner_id_spent_on', ['owner_id', 'spent_on'], unique=False)

    op.create_table('fixed_expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('anchor_calendar', sa.String(length=10), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('end_month', sa.Integer(), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_fixed_expenses_category_id_categories')),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_fixed_expenses_owner_id_owners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fixed_expenses'))
    )
    with op.batch_alter_table('fixed_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixed_expenses_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixed_expenses_owner_id'), ['owner_id'], unique=False)

    op.create_table('settlements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fixed_expense_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('settled_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['fixed_expense_id'], ['fixed_expenses.id'], name=op.f('fk_settlements_fixed_expense_id_fixed_expenses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements')),
    sa.UniqueConstraint('fixed_expense_id', 'period_year', 'period_month', name='one_settlement_per_period')
    )
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlements_fixed_expense_id'), ['fixed_expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlements_owner_id'))
        batch_op.drop_index(batch_op.f('ix_settlements_fixed_expense_id'))

    op.drop_table('settlements')
    with op.batch_alter_table('fixed_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixed_expenses_owner_id'))
        batch_op.drop_index(batch_op.f('ix_fixed_expenses_category_id'))

    op.drop_table('fixed_expenses')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_expenses_owner_id_spent_on')
        batch_op.drop_index(batch_op.f('ix_expenses_owner_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_category_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('ix_categories_owner_id_is_archived')
        batch_op.drop_index(batch_op.f('ix_categories_owner_id'))

    op.drop_table('categories')
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owners_email'))

    op.drop_table('owners')
    # ### end Alembic commands ###
